name: personal_website
description: Personal Website

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  scrollable_positioned_list: ^0.3.8
  font_awesome_flutter: ^10.6.0
  universal_html: ^2.2.4
  auto_size_text: ^3.0.0
  fluttertoast: ^8.2.2
  url_strategy: ^0.2.0
  url_launcher: ^6.1.14
  google_fonts: ^6.1.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - "assets/images/"

    - "assets/images/projects/aler/"
    - "assets/images/projects/ividya/"
    - "assets/images/projects/oratorz/"
    - "assets/images/projects/encourage/"
    - "assets/images/projects/flashchat/"
    - "assets/images/projects/wpd/"
    - "assets/images/projects/roto/"
    - "assets/images/projects/ecomm/"

    - "assets/images/work/atl/"
    - "assets/images/work/desinno/"
    - "assets/images/work/solvrz/"

    - "assets/images/awards/ai/"
    - "assets/images/awards/atl1/"
    - "assets/images/awards/atl2/"
    - "assets/images/awards/desinno/"
    - "assets/images/awards/ift/"
    - "assets/images/awards/robozest/"
    - "assets/images/awards/techie/"
